
// class Autogenerated {
//   String kind;
//   List<ColumnHeaders> columnHeaders;
//   List<List> rows;

//   Autogenerated({this.kind, this.columnHeaders, this.rows});

//   Autogenerated.fromJson(Map<String, dynamic> json) {
//     kind = json['kind'];
//     if (json['columnHeaders'] != null) {
//       // ignore: deprecated_member_use
//       columnHeaders = new List<ColumnHeaders>();
//       json['columnHeaders'].forEach((v) {
//         columnHeaders.add(new ColumnHeaders.fromJson(v));
//       });
//     }
//     if (json['rows'] != null) {
//       // ignore: deprecated_member_use
//       rows = new List<List>();
//       json['rows'].forEach((v) {
//         rows.add(new List.fromJson(v));
//       });
//     }
//   }

//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['kind'] = this.kind;
//     if (this.columnHeaders != null) {
//       data['columnHeaders'] =
//           this.columnHeaders.map((v) => v.toJson()).toList();
//     }
//     if (this.rows != null) {
//       data['rows'] = this.rows.map((v) => v.toJson()).toList();
//     }
//     return data;
//   }
// }


// class ColumnHeaders {
// 	String name;
// 	String columnType;
// 	String dataType;

// 	ColumnHeaders({this.name, this.columnType, this.dataType});

// 	ColumnHeaders.fromJson(Map<String, dynamic> json) {
// 		name = json['name'];
// 		columnType = json['columnType'];
// 		dataType = json['dataType'];
// 	}

// 	Map<String, dynamic> toJson() {
// 		final Map<String, dynamic> data = new Map<String, dynamic>();
// 		data['name'] = this.name;
// 		data['columnType'] = this.columnType;
// 		data['dataType'] = this.dataType;
// 		return data;
// 	}
// }

// class Rows {


// 	Rows({});

// 	Rows.fromJson(Map<String, dynamic> json) {
// 	}

// 	Map<String, dynamic> toJson() {
// 		final Map<String, dynamic> data = new Map<String, dynamic>();
// 		return data;
// 	}
// }